sudo: false
language: node_js
node_js:
  - v8
before_install:
  - cp _config.yml _config.prod.yml
  - npm install -g bower
  - bower install
  - gem install bundler
  - bundle install
  - bundle exec jekyll build
install:
  - npm install
  - npm run build
