sudo: false
language: node_js
node_js:
  - v10
before_install:
  - cp _config.yml _config.prod.yml
  - gem install bundler
  - bundle install --path vendor/bundle
  - npm install
install:
  - npm run build
