title: Chris Vogt, Software Engineer in San Francisco
description: >
  Software Engineer in San Francisco, sharing open source projects
  written in JavaScript and PHP.
banner_image_url: https://res.cloudinary.com/chrisvogt/image/upload/v1482915326/og-image_a1i3rp.png
baseurl: ''
locale: en-US
permalink: /blog/:categories/:slug
url: https://www.chrisvogt.me

analytics_id: UA-33558417-1

instagram:
  access_token: 0000000000.0000000.00000000000000000000000000000000
  client_id: 00000000000000000000000000000000
  user_id: 0000000000

social:
  instagram_username: c1v0
  twitter_username: c1v0
  goodreads_link: https://www.goodreads.com/user/show/10454947-chris-vogt

strings:
  bio: >
    Chris Vogt is a software engineer who works on digital marketing products
    and lives in San Francisco. He enjoys reading science fiction, capturing
    photos and drone footage, playing piano and brewing beer.
  brand: chrisvogt.me
  name: Chris Vogt
  subhead: Software Engineer <span>in San Francisco</span>
  title: Chris Vogt — Software Engineer in San Francisco

theme_options:
  show_credits: true

plugins:
  - jekyll-feed

destination: './_build'
sass:
  sass_dir: ./assets/styles
  style: compressed

exclude:
  - design
  - empty
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bower.json
  - bower_components
  - node_modules
  - package-lock.json
  - package.json
  - vendor-packages.txt
